version: "3.7"

services:

  db_projeto01:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto01_database
    volumes:
      - pgdata:/data/postgresql

  app:
    build: .
    container_name: projeto01
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto01
    depends_on:
      - db_projeto01

volumes:
  pgdata:
    driver: local
