version: "3.8"

services:

  db_projeto01:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - pgdata:/data/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=

  app:
    build: .
    container_name: projeto01
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto01
      - redis
    depends_on:
      - db_projeto01
      - redis

volumes:
  pgdata:
    driver: local
