name: CI

on: 
  push:
    branches: [ master ]
    
  workflow_dispatch: 

jobs: 
  build:
    runs-on: ubunt-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 20.x
      
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          source: "., !node_modules"
          target: "test"
        
        
